In [1]:
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Models
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Evaluation
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("ufc_fight_stats.csv")

# Preview data
df.head()

                                    EVENT  ...  GROUND
0  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0
1  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0
2  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0
3  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0
4  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0

[5 rows x 19 columns]

In [3]:
# Check missing values
df.isnull().sum()

# Drop rows with missing values (or use fillna if preferred)
df = df.dropna()

# Reset index
df.reset_index(drop=True, inplace=True)

In [5]:
for col in df.select_dtypes(include=['object', 'string']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    label_encoders[col] = le

In [7]:
target = 'winner'

if target in df.columns:
    X = df.drop(columns=[target])
    y = df[target]
else:
    print(f"Column '{target}' not found. Available columns:")
    print(df.columns)

Column 'winner' not found. Available columns:
Index(['EVENT', 'BOUT', 'ROUND', 'FIGHTER', 'KD', 'SIG.STR.', 'SIG.STR. %',
       'TOTAL STR.', 'TD', 'TD %', 'SUB.ATT', 'REV.', 'CTRL', 'HEAD', 'BODY',
       'LEG', 'DISTANCE', 'CLINCH', 'GROUND'],
      dtype='str')

In [10]:
df.columns = df.columns.str.strip()  # removes hidden spaces
print(df.columns)           # labels

Index(['EVENT', 'BOUT', 'ROUND', 'FIGHTER', 'KD', 'SIG.STR.', 'SIG.STR. %',
       'TOTAL STR.', 'TD', 'TD %', 'SUB.ATT', 'REV.', 'CTRL', 'HEAD', 'BODY',
       'LEG', 'DISTANCE', 'CLINCH', 'GROUND'],
      dtype='str')

In [11]:
print(df.columns.tolist())

['EVENT', 'BOUT', 'ROUND', 'FIGHTER', 'KD', 'SIG.STR.', 'SIG.STR. %', 'TOTAL STR.', 'TD', 'TD %', 'SUB.ATT', 'REV.', 'CTRL', 'HEAD', 'BODY', 'LEG', 'DISTANCE', 'CLINCH', 'GROUND']

In [14]:
print(df.head())

                                    EVENT  ...  GROUND
0  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0
1  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0
2  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0
3  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0
4  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0

[5 rows x 19 columns]

In [19]:
print(df.columns)

Index(['EVENT', 'BOUT', 'ROUND', 'FIGHTER', 'KD', 'SIG.STR.', 'SIG.STR. %',
       'TOTAL STR.', 'TD', 'TD %', 'SUB.ATT', 'REV.', 'CTRL', 'HEAD', 'BODY',
       'LEG', 'DISTANCE', 'CLINCH', 'GROUND'],
      dtype='str')

In [23]:
print(df.head())
print(df.columns)

                                    EVENT  ...  GROUND
0  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0
1  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0
2  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0
3  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0
4  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0

[5 rows x 19 columns]
Index(['EVENT', 'BOUT', 'ROUND', 'FIGHTER', 'KD', 'SIG.STR.', 'SIG.STR. %',
       'TOTAL STR.', 'TD', 'TD %', 'SUB.ATT', 'REV.', 'CTRL', 'HEAD', 'BODY',
       'LEG', 'DISTANCE', 'CLINCH', 'GROUND'],
      dtype='str')

In [28]:
print(df.columns)

Index(['EVENT', 'BOUT', 'ROUND', 'FIGHTER', 'KD', 'SIG.STR.', 'SIG.STR. %',
       'TOTAL STR.', 'TD', 'TD %', 'SUB.ATT', 'REV.', 'CTRL', 'HEAD', 'BODY',
       'LEG', 'DISTANCE', 'CLINCH', 'GROUND'],
      dtype='str')

In [32]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [33]:
df.head()

                                    EVENT  ...  GROUND
0  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0
1  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0
2  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0
3  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0
4  UFC Fight Night: Dolidze vs. Hernandez  ...  0 of 0

[5 rows x 19 columns]

In [37]:
print(X.dtypes)

EVENT             str
BOUT              str
ROUND             str
FIGHTER           str
KD            float64
SIG.STR.          str
SIG.STR. %        str
TOTAL STR.        str
TD                str
TD %              str
SUB.ATT       float64
REV.          float64
CTRL              str
HEAD              str
BODY              str
LEG               str
DISTANCE          str
CLINCH            str
dtype: object

In [42]:
print(X.isna().sum())
print(y.isna().sum())

KD                                                               42
SUB.ATT                                                          42
REV.                                                             42
EVENT_Ortiz vs Shamrock 3: The Final Chapter                      0
EVENT_The Ultimate Fighter: A Champion Will Be Crowned Finale     0
                                                                 ..
CLINCH_9 of 19                                                    0
CLINCH_9 of 20                                                    0
CLINCH_9 of 21                                                    0
CLINCH_9 of 24                                                    0
CLINCH_9 of 9                                                     0
Length: 26723, dtype: int64
42